datas = [
    {"name": "Rajinikanth", "films_count": 170},
    {"name": "Kamal Haasan", "films_count": 230},
    {"name": "Vijay", "films_count": 65},
    {"name": "Ajith Kumar", "films_count": 60},
    {"name": "Suriya", "films_count": 45},
    {"name": "Vikram", "films_count": 55},
    {"name": "Dhanush", "films_count": 44},
    {"name": "Samantha Ruth Prabhu", "films_count": 50},
    {"name": "Nayanthara", "films_count": 75},
    {"name": "Trisha", "films_count": 60},
    {"name": "Jayam Ravi", "films_count": 35},
    {"name": "Sivakarthikeyan", "films_count": 25},
    {"name": "Arya", "films_count": 30},
    {"name": "Vijay Sethupathi", "films_count": 50},
    {"name": "Anushka Shetty", "films_count": 40},
    {"name": "Hansika Motwani", "films_count": 50},
    {"name": "Jiiva", "films_count": 30},
    {"name": "Keerthy Suresh", "films_count": 25},
    {"name": "Aishwarya Rajesh", "films_count": 30},
    {"name": "Karthi", "films_count": 25},
    # Adding 20 more celebrities
    {"name": "Silambarasan TR (STR)", "films_count": 45},
    {"name": "Vishal", "films_count": 35},
    {"name": "Rakul Preet Singh", "films_count": 35},
    {"name": "Tamannaah Bhatia", "films_count": 65},
    {"name": "Prabhu Deva", "films_count": 50},
    {"name": "Amala Paul", "films_count": 30},
    {"name": "Lakshmi Menon", "films_count": 20},
    {"name": "Nadhiya", "films_count": 50},
    {"name": "Bobby Simha", "films_count": 30},
    {"name": "Meena", "films_count": 85},
    {"name": "R. Madhavan", "films_count": 40},
    {"name": "Sarathkumar", "films_count": 130},
    {"name": "Bhagyaraj", "films_count": 75},
    {"name": "Jyothika", "films_count": 50},
    {"name": "Ramya Krishnan", "films_count": 70},
    {"name": "Kajal Aggarwal", "films_count": 60},
    {"name": "Simran", "films_count": 60},
    {"name": "Shruti Haasan", "films_count": 35},
    {"name": "Nivetha Pethuraj", "films_count": 20},
    {"name": "Radha Ravi", "films_count": 200}
]
